### ISSUE TITLE
Re-categorize your repo 

### ISSUE THREAD

**Issue by ciaranBarterm** [JubairRahman/Desigin#1]
This repo is not professional. Need to re-categorize it.

**Comment by JubairRahman** [comment]
This was my first repo. I opened this for demo.

**Comment by ciaranBarterm** [comment]
Then you should redesign your very first repo.

**Comment by JubairRahman** [comment]
I will make this repo private.

**Comment by ciaranBarterm** [comment]
It will be more effective
